name: docker

on:
  workflow_dispatch:
permissions:
  contents: write 
  packages: write 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup qemu
      uses: docker/setup-qemu-action@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: login docker hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: login github container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo "build_tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        provenance: false
        platforms: linux/amd64,linux/386,linux/s390x,linux/arm64,linux/arm/v7
        push: true
        tags: |
          docker.io/${{ github.repository_owner }}/shortener:latest
          docker.io/${{ github.repository_owner }}/shortener:${{ env.build_tag }}
          ghcr.io/${{ github.repository_owner }}/shortener:latest
          ghcr.io/${{ github.repository_owner }}/shortener:${{ env.build_tag }}
